# Generated by Django 3.2.7 on 2021-09-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='filename')),
                ('x_axis_180', models.IntegerField(verbose_name='x_axis_180')),
                ('y_axis_90', models.IntegerField(verbose_name='y_axis_90')),
                ('diagonal_45', models.IntegerField(verbose_name='diagonal_45')),
                ('diagonal_135', models.IntegerField(verbose_name='diagonal_135')),
                ('all', models.IntegerField(verbose_name='all')),
                ('none', models.IntegerField(verbose_name='none')),
            ],
        ),
    ]
